services:
  db:
    image: postgres:15
    container_name: lionfit-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sbermudez1}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sebas24061}
      POSTGRES_DB: ${POSTGRES_DB:-Lion-Fit-Pro}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: lionfit-api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "npx prisma migrate deploy && node src/server.js"

volumes:
  db_data:
